metric: Fix the error: could not convert {...} from <brace-enclosed initializer list> to struct metric_definition_impl
When using gcc4.9.2 to compile seastar, the above error occurred.
The reason was default member initializer prevented the class from being an aggregate.

This patch added a constructor for struct metric_definition_impl.

Ref:
http://stackoverflow.com/questions/37776823/could-not-convert-from-brace-enclosed-initializer-list-to-struct

Error message:
[root@localhost seastar]# ninja-build
[7/106] CXX build/release/net/ip.o
FAILED: /usr/local/bin/g++ -MMD -MT build/release/net/ip.o -MF build/release/net/ip.o.d -O2 -I build/release/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -Ifmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DNO_EXCEPTION_INTERCEPT -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/net/ip.o net/ip.cc
In file included from net/ip.cc:28:0:
./core/metrics.hh: In instantiation of 'seastar::metrics::impl::metric_definition_impl seastar::metrics::make_derive(seastar::metrics::metric_name_type, T&&, seastar::metrics::description, bool, seastar::metrics::instance_id_type, seastar::metrics::metric_type_def) [with T = net::ipv4::ipv4(net::interface*)::<lambda()>; seastar::metrics::metric_name_type = basic_sstring<char, unsigned int, 15u>; seastar::metrics::instance_id_type = basic_sstring<char, unsigned int, 15u>; seastar::metrics::metric_type_def = basic_sstring<char, unsigned int, 15u>]':
net/ip.cc:70:144:   required from here
./core/metrics.hh:287:133: error: could not convert '{name, instance, {DERIVE, iht}, seastar::metrics::impl::make_function(T, seastar::metrics::impl::data_type) [with T = net::ipv4::ipv4(net::interface*)::<lambda()>; <template-parameter-1-2> = void; seastar::metrics::impl::metric_function = std::function<seastar::metrics::impl::metric_value()>]((seastar::metrics::impl::data_type)2u), d, enabled}' from '<brace-enclosed initializer list>' to 'seastar::metrics::impl::metric_definition_impl'
     return {name, instance, {impl::data_type::DERIVE, iht}, make_function(std::forward<T>(val), impl::data_type::DERIVE), d, enabled};

Signed-off-by: Javeme Lee <javaloveme@gmail.com>
Message-Id: <20170123062548.73534-1-javaloveme@gmail.com>